default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_language_version:
    python: python3.10

ci:
    skip: [pytest-check, commit-msg-hook]
    autofix_commit_msg: |
        🚧 build: [pre-commit.ci] auto fixes from pre-commit.com hooks
    autofix_prs: true
    autoupdate_schedule: weekly
    autoupdate_commit_msg: |
        🚧 build: [pre-commit.ci] pre-commit autoupdate

repos:
-   repo: https://github.com/asottile/pyupgrade
    rev:  v3.20.0
    hooks:
    -   id: pyupgrade
        args: [
            "--py310-plus",
            "--keep-runtime-typing",
        ]
        stages: [pre-commit]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        stages: [pre-commit]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev:  v0.13.0
    hooks:
    -   id: ruff
        args: ["--fix"]
        stages: [pre-commit]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev:  v6.0.0
    hooks:
    -   id: fix-byte-order-marker
        stages: [pre-commit]
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: check-yaml
        args: ["--unsafe"]
        exclude: ".*spark_job.yml"
        stages: [pre-commit]
    -   id: check-toml
        stages: [pre-commit]

-   repo: https://github.com/korawica/clishelf
    rev: v0.2.23
    hooks:
    -   id: shelf-commit-msg
