from pathlib import Path

from airflow.models import DAG

from dagtool.factory import Factory


def test_factory(test_path: Path):
    factory = Factory("sales_dag", path=test_path / "demo")
    print(factory)
    print(factory.conf)


def test_factory_build(test_path: Path):
    factory = Factory(name="demo", path=test_path / "demo")
    dags: list[DAG] = factory.build()
    assert len(dags) == 1


def test_factory_build_to_globals(test_path: Path):
    factory = Factory(
        name="demo",
        docs="# Demo DAGS\n\nThe demo DAGS\n",
        path=test_path / "demo",
    )
    factory.build_airflow_dags_to_globals(
        gb=globals(),
        default_args={"start_date": "2025-01-01 00:00:00"},
    )
    dag: DAG = globals().get("demo_sales_dag")
    assert dag.dag_id == "demo_sales_dag"
    assert dag.doc_md == (
        "# Demo DAGS\n\nThe demo DAGS\n\nNone\n\n### YAML Template\n\n"
        "````yaml\n"
        "name: sales_dag\n"
        "type: dag\n"
        'start_date: "2025-01-01"\n'
        'schedule: "@daily"\n'
        'authors: ["de-team"]\n'
        "tags:\n"
        "  - sales\n "
        " - p1\n"
        "tasks:\n"
        "  - task: start\n"
        "    tool: empty\n\n"
        "  - group: task_group\n"
        "    upstream: start\n"
        "    tasks:\n"
        "      - task: sub_task\n"
        "        tool: empty\n\n"
        "  - task: end\n"
        "    upstream: task_group\n"
        "    tool: empty\n\n"
        "````\n"
        "> Generated by DAG Tools HASH: "
        "`cc86e3a493f283cea3c8e5363cfe30327167033ad7ace6b771dd6f0aca24678f`."
    )
