name: dukdig-local
services:
  airflow:
    image: airflow-local
    container_name: airflow-dev
    build:
      context: ..
      dockerfile: ./.container/Dockerfile
    ports:
      - "8080:8080"
    command: [ "airflow", "standalone" ]
    environment:
      AIRFLOW_HOME: /root/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: False
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.default
      AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 1
      AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: 1
    volumes:
      - ${pwd}/dags/:/root/airflow/dags
